### ISSUE TITLE
Types not working with vite project

### ISSUE THREAD

**Issue by gkiely** [kriasoft/web-auth-library#19]
Steps:
```
git clone https://github.com/gkiely/vite-project
cd vite-project
npm i
code .
```

Open server.ts
<img width="818" alt="image" src="https://user-images.githubusercontent.com/1948935/232457823-45acb370-e094-4c1d-9e70-66e93ee2ab76.png">

**Comment by motiejunas** [comment]
Please fix.

**Comment by koistya** [comment]
@gkiely I'm checking your repo but am unable to reproduce this issue

![image](https://github.com/kriasoft/web-auth-library/assets/197134/994bfefe-1d00-46f1-ad7f-f8ff2f40d4ae)

**Comment by gkiely** [comment]
Looks like it's working!
